spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password: admin12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:mariadb://localhost:3306/product-manager
    schemas: product-manager
    user: "root"
    password: "admin12345"
